crm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls", namespace='webapp'))
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = "webapp"

urlpatterns = [
    path("", views.landing_page, name="home"),
    path("register", views.register, name="register"),
    path("login", views.my_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    # CRUD
    path("dashboard", views.dashboard, name="dashboard"),
    path("view-record/<int:pk>", views.view_record, name="record"),
    path("create-record", views.create_record, name="create"),
    path("update-record/<int:pk>", views.update_record, name="update"),
    path("delete-record/<int:pk>", views.delete_record, name="delete"),
]

webapp/models.py
from django.db import models
from crm.settings import DEFAULT_AUTO_FIELD

class Record(models.Model):

    creation_date = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=10)

    address = models.CharField(max_length=300)

    city = models.CharField(max_length=20)
    province = models.CharField(max_length=20)

    country = models.CharField(max_length=20)

    def __str__(self):
        return self.first_name + "  " + self.last_name

webapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms

from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from webapp.models import Record

# Register/Create a user

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username',
                  'email',
                  'password1',
                  'password2']
        

# Login User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())


# Create Records

class CreateRecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = "__all__"


# Update Records

class UpdateRecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = "__all__"

webapp/views.py
import django
from django.shortcuts import render, redirect
from .forms import *

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from .models import Record

from django.contrib import messages

# Homepage

def landing_page(request):
    return render(request, "webapp/index.html")

# Register

def register(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, "Account created successfully!")

            return redirect("webapp:login")
    
    context = {
        'form': form,
    }
    
    return render(request, "webapp/register.html", context)

# Login

def my_login(request):
    form = LoginForm()

    if request.method == "POST":

        form = LoginForm(request, data=request.POST)

        if form.is_valid():

            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)

                messages.success(request, "You are Logged In!")


                return redirect("webapp:dashboard")
            

    context = {
        'form': form,
    }

    return render(request, "webapp/my-login.html", context)


# Dashboard

@login_required(login_url="webapp:login")
def dashboard(request):

    records = Record.objects.all()

    context = {
        "records": records,
    }

    return render(request, "webapp/dashboard.html", context)
    
# Logout

def user_logout(request):
    logout(request)

    messages.success(request, "You are Logged out! 👋👋👋")


    return redirect("webapp:login")



# Read / View a singular Record
@login_required(login_url="webapp:login")
def view_record(request,pk):
    record = Record.objects.get(id=pk)
    context = {'record': record}

    return render(request, "webapp/view-record.html", context)



# Create a record

@login_required(login_url="webapp:login")
def create_record(request):
    form = CreateRecordForm()

    if request.method == "POST":
        form = CreateRecordForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, "Your record was created!")

            return redirect("webapp:dashboard")
        
    context = {
        'form': form
    }

    return render(request, "webapp/create.html", context)

# Update a record

@login_required(login_url="webapp:login")
def update_record(request, pk):
    record = Record.objects.get(id=pk)
    form = UpdateRecordForm(instance=record)

    if request.method == "POST":
        form = UpdateRecordForm(request.POST, instance=record)

        if form.is_valid():
            form.save()

            messages.success(request, "Your record was updated!")


            return redirect("webapp:dashboard")
        
    context = {
        'form': form
    }

    return render(request, "webapp/update.html", context)

# Delete a record

@login_required(login_url="webapp:login")
def delete_record(request, pk):
    record = Record.objects.get(id=pk)
    record.delete()

    messages.success(request, "Your record was deleted!")


    return redirect("webapp:dashboard")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ProjectX</title>
  <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/darkly/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
  <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
  <!-- Create a navbar here -->
  {% include "webapp/navbar.html" %}

  <div class="container">
    <br />

    <!-- Notification messages -->
    {% for message in messages %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

    <p id="message-timer" class="alert alert-success float-center text-center message-text"> <i class="fa-solid fa-check"></i> &nbsp;
      {{message}}</p>

    {% endif %}

    {% endfor %}

    {% block content %} {% endblock content %}

  </div>
  <script src="{% static 'js/app.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
    integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
    crossorigin="anonymous"></script>

</body>

</html>

templates/webapp/create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<body>
    <div class="container bg-light shadow-md p-5 form-layout">

        <h3>Create a record</h3>
        <p>Start adding required fields as per the requirements!</p>

        <hr>
        <br>

        <form method="POST" autocomplete="off">
            {% csrf_token %}

            {{form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary ">Create a record &nbsp; <i class="fa-solid fa-user-plus"></i>
            </button>

            <a href="{% url 'webapp:dashboard' %}" class="btn btn-secondary"><i class="fa-regular fa-circle-left"></i>
                &nbsp; Return
            </a>

        </form>

        <br>
    </div>

    <br>
</body>

{% endblock content %}

templates/webapp/dashboard.html
{% extends "base.html" %}

{% block content %}
<h5 class="text-center">Welcome to the Dashboard {{ user }}!👋</h5>
<hr>
<a class="btn btn-outline-primary btn-sm" href="{% url 'webapp:create' %}">
    Create a new record &nbsp; <i class="fa-solid fa-user-pen"></i>
</a>
<hr>

<table class="table table-dark table-bordered">
    <thead class="table-primary">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Full Name</th>
            <th scope="col">Email</th>
            <th scope="col">Address</th>
            <th scope="col">City</th>
            <th scope="col">Province</th>
            <th scope="col">Country</th>
            <th scope="col">Date Joined</th>

            <th scope="col">View</th>

        </tr>
    </thead>

    <tbody>
        {% if records %}

        {% for record in records %}

        <tr>
            <td>{{record.id}}</td>
            <td>{{record.first_name}} {{record.last_name}}</td>
            <td>{{record.email}}</td>
            <td>{{record.address}}</td>
            <td>{{record.city}}</td>
            <td>{{record.province}}</td>
            <td>{{record.country}}</td>
            <td>{{record.creation_date}}</td>

            <td><a href="{% url 'webapp:record' record.pk %}"><i class="fa-regular fa-eye"></i></a></td>
        </tr>

        {% endfor %}

        {% endif %}
    </tbody>

</table>

{% endblock content %}

templates/webapp/index.html
{% extends "base.html" %} {% block content %}

<body>
    <br>
    <br>

    <div class="text-center">
        <h3>ProjectX Management at it's finest! </h3>

        <br>

        <h5> Keep track of your records effectively! </h5>

        <hr>

        <br>

        <a class="btn btn-primary" type="button" href="{% url 'webapp:register' %}">Create your account &nbsp; <i class="fa-solid fa-users"></i> </a>
    </div>
</body>

{% endblock content %}

templates/webapp/my-login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<body>
    <div class="container bg-light shadow-md p-5 form-layout">

        <h3>Login to your account</h3>

        <hr>
        <br>

        <form method="POST" autocomplete="off">
            {% csrf_token %}

            {{form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary w-100 btn-block p-2">Login &nbsp; <i
                    class="fa-solid fa-key"></i></button>

        </form>

        <br>

        <div class="text-center">
            <p class="">Don't have an account?</p> <a href="{% url 'webapp:register' %}">Register</a>
        </div>

    </div>

    <br>
</body>

{% endblock content %}

templates/webapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-center">

    <a class="navbar-brand main-heading" href="{% url 'webapp:home' %}">

        &nbsp; ProjectX

    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>

    </button>


    <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">


        <ul class="navbar-nav mr-auto">


            &nbsp; &nbsp; &nbsp;

            {% if user.is_authenticated %}

            <li class="nav-item">

                <a class="nav-link" href="{% url 'webapp:dashboard' %}">Dashboard &nbsp; <i class="fa fa-home"
                        aria-hidden="true"></i>
                </a>

            </li>


            &nbsp; &nbsp; &nbsp;


            <li class="nav-item">

                <a class="nav-link" href="{% url 'webapp:logout' %}">Sign out &nbsp; <i class="fa fa-sign-out"
                        aria-hidden="true"></i> </a>

            </li>


        </ul>

        {% else %}

        <li class="nav-item">

            <a class="nav-link" href="{% url 'webapp:register' %}"> Register &nbsp; <i class="fa-solid fa-user-plus"></i></a>

        </li>


        &nbsp; &nbsp; &nbsp;


        <li class="nav-item">

            <a class="nav-link" href="{% url 'webapp:login' %}">Login &nbsp; <i class="fa-solid fa-user"></i></a>

        </li>


        {% endif %}


    </div>


</nav>

templates/webapp/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<body>
    <div class="container bg-light shadow-md p-5 form-layout">

        <h3>Create your account</h3>

        <h5> Start managing your clients today!</h5>

        <hr>
        <br>

        <form method="POST" autocomplete="off">
            {% csrf_token %}

            {{form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary w-100 btn-block p-2">Create account &nbsp; <i
                    class="fa-solid fa-user-plus"></i></button>

        </form>

        <br>

        <div class="text-center">
            <p>Already have an account?</p> <a href="{% url 'webapp:login' %}">Login</a>
        </div>

    </div>

    <br>
</body>

{% endblock content %}

templates/webapp/update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<body>
    <div class="container bg-light shadow-md p-5 form-layout">

        <h3>Update the record</h3>

        <hr>
        <br>

        <form method="POST" autocomplete="off">
            {% csrf_token %}

            {{form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary">Update the record</button>

            <a href="{% url 'webapp:dashboard' %}" class="btn btn-secondary"><i class="fa-regular fa-circle-left"></i>
                &nbsp; Return
            </a>

        </form>

        <br>
    </div>

    <br>
</body>

{% endblock content %}

templates/webapp/view-record.html
{% extends "base.html" %}

{% block content %}

<div class="card">
    <div class="card-body">

        <strong class="text-center">
            <i class="fa fa-user-circle-o"></i>
            &nbsp;
            {{ record.last_name | upper }}
            {{ record.first_name | upper }}
        </strong>
        <hr>
        <p><strong>ID:</strong>{{record.id}}</p>
        <p><strong>Full Name:</strong> {{record.first_name}} {{record.last_name}}</p>
        <p><strong>Email:</strong> {{record.email}}</p>
        <p><strong>Phone Number:</strong> {{record.phone}}</p>
        <p><strong>Address:</strong> {{record.address}}</p>
        <p><strong>City:</strong> {{record.city}}</p>
        <p><strong>Province:</strong> {{record.province}}</p>
        <p><strong>Country:</strong> {{record.country}}</p>
        <p><strong>Date Joined:</strong> {{record.creation_date}}</p>

    </div>
</div>
<hr>
<a href="{% url 'webapp:dashboard' %}" class="btn btn-secondary"><i class="fa-regular fa-circle-left"></i> &nbsp; Return
</a>
&nbsp;
<a href="{% url 'webapp:update' record.pk %}" class="btn btn-info">Update record &nbsp; <i
        class="fa-solid fa-user-pen"></i></a>
&nbsp;

<a href="{% url 'webapp:delete' record.pk %}" class="btn btn-danger">Delete record &nbsp; <i
        class="fa-solid fa-user-xmark"></i></a>

{% endblock content %}